### ISSUE TITLE
Add DUO, new package manager

### ISSUE THREAD

**Issue by rovansteen** [flovan/headstart#34]
You said you didn't want to add Bower because of the way Headstart's folder structure is organized. Perhaps DUO (http://duojs.org/) is something that fits better. Looks very promising to me.

I'm not sure how to add it to Headstart, so I couldn't make a pull request. 
There is an example for Gulp here: https://github.com/duojs/duo/tree/master/examples/gulpfile

Would love to see a package manager added to Headstart.

**Comment by flovan** [comment]
@MatthewMueller I mailed you a summary of my problem. I guess I could've just pinged like I just did, but what's done's done :grin:

Again, here's the config section for Duo that I'd like to use:

````javascript
"duo": {
	"libs": ["jquery/jquery@1.11.2", "lodash/lodash@2.4.1", "ftlabs/fastclick@1.0.3"],
	"libs/dev": ["kayahr/console-shim"],
	"ie/head": ["aFarkas/html5shiv@3.7.2"],
	"ie/body": ["ie-behavior-span", "scottjehl/Respond@1.4.2"]
}
````

The goals is to loop over this, and create a file per section (4 in this case), and write each bundled file to the target folder (the key). My current attempt to do just that:

````javascript
deps.lodash.forIn(settings.config.duo, function (value, key) {
	// Set the download dir
	duo.installTo('./duo-components/' + key);

	// Fetch individual components
	deps.lodash.each(value, function (module) {
		duo.include(module).run(function (err, src) {
		if (err) console.log('err', err);
			console.log('src', src);
		});;
	});
});
````

**Comment by flovan** [comment]
Success! But with a few gotchas... Poke @rovansteen.

First off, I don't find the configuration part to be more intuitive/easier than how it is right now (downloading manually):

`.headstartrc` (new config name for V2):
````javascript
{
	[...],
	
	"duo": {
		"libs": ["jquery/jquery@1.11.2:dist/jquery.js", "lodash/lodash@2.4.1", "ftlabs/fastclick@v1.0.3"],
		"libs/dev": ["kayahr/console-shim@master:console-shim.js"],
		"ie/head": ["aFarkas/html5shiv@3.7.2:dist/html5shiv.js"],
		"ie/body": ["UmbraEngineering/Placeholder@master:src/ie-behavior-span.js", "scottjehl/Respond@1.4.2:dest/respond.min.js"]
	}
}
````

Just look at all those specific targets! If there is a release available, you need `@x.x.x`, or in the case of Fastclick, where the author used a different naming, you need `@v.x.x.x`. If the component doesn't contain a Bower config file, it makes things harder. You have to find the file you want, and add that too; `:nested/folder/file.js`. But then there are exceptions. jQuery has a Bower config, but it wasn't included in the build until I also pointed at it's location. And last, when there are no releases, and the file is in the root, you'd expect things to go down easy, but if there are multiple branches, you have to specify the branch `@master` or you might end up with a different one.

To me, that looks like a mighty list of big no-no's compared to just downloading the zip from Github.

But there's one more thing; all files get concatenated and exposed through a module, which means that you'll have to require the same lengthy strings again in your JS files, eg. `var $ = require('jquery/jquery@1.11.2:dist/jquery.js');`, OR they can be exposed through a global, eg `deps.$` or `deps.Fastclick`, but that will likely result in conflicts as we're not dealing with one but [multiple Duo builds](https://github.com/flovan/headstart/blob/70df0f1afdd6f25721ced7d1974049353f900afc/lib/tasks/init.js#L27-L67).

</rant>

I think I'm going to go find something else to use as this is just plain madness, no? Or maybe I have to rethink the way I use dependencies right now. Is the structure that important? I think yes, but please let me know if you think otherwise.
